<a href="https://colab.research.google.com/github/Kishoby/Churn_Prediction_ML/blob/Test_Split/Churn_Test_Split.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
import os

In [2]:
df = pd.read_csv(
    "/content/drive/MyDrive/Project_Churn Prediction/02_Feature_Engineering/Telco_Customer_Churn_Feature_Engineered.csv"
)

print("Dataset Loaded Successfully")
print("Dataset Shape:", df.shape)

display(df.head())

Dataset Loaded Successfully
Dataset Shape: (7032, 59)

,SeniorCitizen,tenure,MonthlyCharges,TotalCharges,Churn,gender_Male,Partner_Yes,Dependents_Yes,PhoneService_Yes,MultipleLines_No phone service,...,StreamingServiceCount,TotalAdditionalServices,NoSecurityOrTechSupport,HasInternetService,FiberOpticCustomer,HighRiskBillingProfile,ChargesPerContractMonth,Tenure_MonthlyCharges_Interaction,Tenure_ServiceCount_Interaction,MonthlyCharges_ServiceCount_Interaction
0,0,1,29.85,29.85,0,False,True,False,False,True,...,0,1,1,1,0,0,29.850000,29.85,1,29.85
1,0,34,56.95,1889.50,0,True,False,False,True,False,...,0,2,0,1,0,0,4.745833,1936.30,68,113.90
2,0,2,53.85,108.15,1,True,False,False,True,False,...,0,2,0,1,0,0,53.850000,107.70,4,107.70
3,0,45,42.30,1840.75,0,True,False,False,False,True,...,0,3,0,1,0,0,3.525000,1903.50,135,126.90
4,0,2,70.70,151.65,1,False,False,False,True,False,...,0,0,1,1,1,1,70.700000,141.40,0,0.00

In [3]:
print("="*60)
print("DATASET INFORMATION")
print("="*60)

df.info()

============================================================
DATASET INFORMATION
============================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7032 entries, 0 to 7031
Data columns (total 59 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   SeniorCitizen                            7032 non-null   int64
 1   tenure                                   7032 non-null   int64
 2   MonthlyCharges                           7032 non-null   float64
 3   TotalCharges                             7032 non-null   float64
 4   Churn                                    7032 non-null   int64
 5   gender_Male                              7032 non-null   bool
 6   Partner_Yes                              7032 non-null   bool
 7   Dependents_Yes                           7032 non-null   bool
 8   PhoneService_Yes                         7032 non-null   bool
 9   MultipleLines_No phone service           7032 non-null   bool
 10  MultipleLines_Yes                        7032 non-null   bool
 11  InternetService_Fiber optic              7032 non-null   bool
 12  InternetService_No                       7032 non-null   bool
 13  OnlineSecurity_No internet service       7032 non-null   bool
 14  OnlineSecurity_Yes                       7032 non-null   bool
 15  OnlineBackup_No internet service         7032 non-null   bool
 16  OnlineBackup_Yes                         7032 non-null   bool
 17  DeviceProtection_No internet service     7032 non-null   bool
 18  DeviceProtection_Yes                     7032 non-null   bool
 19  TechSupport_No internet service          7032 non-null   bool
 20  TechSupport_Yes                          7032 non-null   bool
 21  StreamingTV_No internet service          7032 non-null   bool
 22  StreamingTV_Yes                          7032 non-null   bool
 23  StreamingMovies_No internet service      7032 non-null   bool
 24  StreamingMovies_Yes                      7032 non-null   bool
 25  Contract_One year                        7032 non-null   bool
 26  Contract_Two year                        7032 non-null   bool
 27  PaperlessBilling_Yes                     7032 non-null   bool
 28  PaymentMethod_Credit card (automatic)    7032 non-null   bool
 29  PaymentMethod_Electronic check           7032 non-null   bool
 30  PaymentMethod_Mailed check               7032 non-null   bool
 31  AverageMonthlySpend                      7032 non-null   float64
 32  TenureGroup_0-12 Months                  7032 non-null   int64
 33  TenureGroup_13-24 Months                 7032 non-null   int64
 34  TenureGroup_25-48 Months                 7032 non-null   int64
 35  TenureGroup_49-60 Months                 7032 non-null   int64
 36  TenureGroup_Above 60 Months              7032 non-null   int64
 37  NewCustomer                              7032 non-null   int64
 38  LongTermCustomer                         7032 non-null   int64
 39  LowMonthlyCharges                        7032 non-null   int64
 40  MediumMonthlyCharges                     7032 non-null   int64
 41  HighMonthlyCharges                       7032 non-null   int64
 42  LowTotalCharges                          7032 non-null   int64
 43  HighTotalCharges                         7032 non-null   int64
 44  ContractDurationMonths                   7032 non-null   int64
 45  MonthToMonthContract                     7032 non-null   int64
 46  LongTermContract                         7032 non-null   int64
 47  AutomaticPayment                         7032 non-null   int64
 48  SupportServiceCount                      7032 non-null   int64
 49  StreamingServiceCount                    7032 non-null   int64
 50  TotalAdditionalServices                  7032 non-null   int64
 51  NoSecurityOrTechSupport                  7032 non-null   int64
 52  HasInternetService                       7032 non-null   int64
 53  FiberOpticCustomer                       7032 non-null   int64
 54  HighRiskBillingProfile                   7032 non-null   int64
 55  ChargesPerContractMonth                  7032 non-null   float64
 56  Tenure_MonthlyCharges_Interaction        7032 non-null   float64
 57  Tenure_ServiceCount_Interaction          7032 non-null   int64
 58  MonthlyCharges_ServiceCount_Interaction  7032 non-null   float64
dtypes: bool(26), float64(6), int64(27)
memory usage: 1.9 MB

In [4]:
print("Missing Values")

display(df.isnull().sum())

Missing Values

SeniorCitizen                              0
tenure                                     0
MonthlyCharges                             0
TotalCharges                               0
Churn                                      0
gender_Male                                0
Partner_Yes                                0
Dependents_Yes                             0
PhoneService_Yes                           0
MultipleLines_No phone service             0
MultipleLines_Yes                          0
InternetService_Fiber optic                0
InternetService_No                         0
OnlineSecurity_No internet service         0
OnlineSecurity_Yes                         0
OnlineBackup_No internet service           0
OnlineBackup_Yes                           0
DeviceProtection_No internet service       0
DeviceProtection_Yes                       0
TechSupport_No internet service            0
TechSupport_Yes                            0
StreamingTV_No internet service            0
StreamingTV_Yes                            0
StreamingMovies_No internet service        0
StreamingMovies_Yes                        0
Contract_One year                          0
Contract_Two year                          0
PaperlessBilling_Yes                       0
PaymentMethod_Credit card (automatic)      0
PaymentMethod_Electronic check             0
PaymentMethod_Mailed check                 0
AverageMonthlySpend                        0
TenureGroup_0-12 Months                    0
TenureGroup_13-24 Months                   0
TenureGroup_25-48 Months                   0
TenureGroup_49-60 Months                   0
TenureGroup_Above 60 Months                0
NewCustomer                                0
LongTermCustomer                           0
LowMonthlyCharges                          0
MediumMonthlyCharges                       0
HighMonthlyCharges                         0
LowTotalCharges                            0
HighTotalCharges                           0
ContractDurationMonths                     0
MonthToMonthContract                       0
LongTermContract                           0
AutomaticPayment                           0
SupportServiceCount                        0
StreamingServiceCount                      0
TotalAdditionalServices                    0
NoSecurityOrTechSupport                    0
HasInternetService                         0
FiberOpticCustomer                         0
HighRiskBillingProfile                     0
ChargesPerContractMonth                    0
Tenure_MonthlyCharges_Interaction          0
Tenure_ServiceCount_Interaction            0
MonthlyCharges_ServiceCount_Interaction    0
dtype: int64

In [5]:
X = df.drop("Churn", axis=1)

y = df["Churn"]

print("Feature Matrix Shape :", X.shape)
print("Target Shape :", y.shape)

Feature Matrix Shape : (7032, 58)
Target Shape : (7032,)

In [6]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

In [7]:
print("Training Features :", X_train.shape)
print("Testing Features  :", X_test.shape)

print()

print("Training Labels :", y_train.shape)
print("Testing Labels  :", y_test.shape)

Training Features : (5625, 58)
Testing Features  : (1407, 58)

Training Labels : (5625,)
Testing Labels  : (1407,)

In [8]:
print("Training Class Distribution")

display(
    y_train.value_counts().to_frame("Count")
)

display(
    round(
        y_train.value_counts(normalize=True)*100,
        2
    ).to_frame("Percentage")
)

Training Class Distribution

       Count
Churn
0       4130
1       1495

       Percentage
Churn
0           73.42
1           26.58

In [9]:
print("Testing Class Distribution")

display(
    y_test.value_counts().to_frame("Count")
)

display(
    round(
        y_test.value_counts(normalize=True)*100,
        2
    ).to_frame("Percentage")
)

Testing Class Distribution

       Count
Churn
0       1033
1        374

       Percentage
Churn
0           73.42
1           26.58

In [10]:
output_path = "/content/drive/MyDrive/Project_Churn Prediction/03_Train_Test_Split"

os.makedirs(output_path, exist_ok=True)

print("Output folder created successfully.")

Output folder created successfully.

In [11]:
train_df = X_train.copy()

train_df["Churn"] = y_train.values

train_df.to_csv(
    f"{output_path}/Training_Dataset.csv",
    index=False
)

print("Training dataset saved.")

Training dataset saved.

In [12]:
test_df = X_test.copy()

test_df["Churn"] = y_test.values

test_df.to_csv(
    f"{output_path}/Testing_Dataset.csv",
    index=False
)

print("Testing dataset saved.")

Testing dataset saved.

In [13]:
X_train.to_csv(
    f"{output_path}/X_train.csv",
    index=False
)

X_test.to_csv(
    f"{output_path}/X_test.csv",
    index=False
)

y_train.to_csv(
    f"{output_path}/y_train.csv",
    index=False
)

y_test.to_csv(
    f"{output_path}/y_test.csv",
    index=False
)

print("Individual train-test files saved.")

Individual train-test files saved.

In [14]:
summary = pd.DataFrame({

    "Dataset":[
        "Training Features",
        "Testing Features",
        "Training Labels",
        "Testing Labels"
    ],

    "Rows":[
        X_train.shape[0],
        X_test.shape[0],
        y_train.shape[0],
        y_test.shape[0]
    ],

    "Columns":[
        X_train.shape[1],
        X_test.shape[1],
        1,
        1
    ]

})

display(summary)

             Dataset  Rows  Columns
0  Training Features  5625       58
1   Testing Features  1407       58
2    Training Labels  5625        1
3     Testing Labels  1407        1

In [15]:
summary.to_csv(
    f"{output_path}/Train_Test_Summary.csv",
    index=False
)

print("Summary saved successfully.")

Summary saved successfully.

In [16]:
import shutil

shutil.make_archive(
    "/content/Train_Test_Split",
    "zip",
    output_path
)

print("ZIP file created successfully.")

ZIP file created successfully.

In [17]:
from google.colab import files

files.download("/content/Train_Test_Split.zip")